replicaCount: 1

image:
  repository: sametdemirel/login-app
  pullPolicy: IfNotPresent
  tag: "1.4.0"

service:
  type: NodePort
  port: 5000
  nodePort: 30080

postgresql:
  host: postgresql.postgres.svc.cluster.local
  port: 5432
  database: appdb
  username: appuser
  password: "PWPTdYa3sM5U7aRC"

redis:
  host: redis-master.redis.svc.cluster.local
  port: 6379
  password: "FDZvgmM32o9ltym4"

app:
  secretKey: "lOF2Ks0pA1vM5Auu"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
